### ISSUE TITLE
external sdcard isn't supported in the latest build?

### ISSUE THREAD

**Issue by Iey4iej3** [jcadduono/android_device_samsung_kltechn#1]
I downloaded the latest build from idlekernel. As far as I've experienced, the latest build doesn't support external sdcard. It seems to me that it's excerpted in BoardConfig.mk

**Comment by jcadduono** [comment]
You're using a L build on an M bootloader, use an M build

**Comment by Iey4iej3** [comment]
Thanks for the response.

I am, in fact, using an M build on a L build. Sorry.
